### ISSUE TITLE
for some reason it won't let me activate the plugin

### ISSUE THREAD

**Issue by drcucaracha** [c-as/godot-voip#10]
![01](https://user-images.githubusercontent.com/49615968/109438729-f1812880-7a09-11eb-8cfd-a22fe9a3a53f.png)

![02](https://user-images.githubusercontent.com/49615968/109438761-0958ac80-7a0a-11eb-97a4-af57f907ed7f.png)

![03](https://user-images.githubusercontent.com/49615968/109438766-0e1d6080-7a0a-11eb-9128-d283b7f5e374.png)

any idea if i did something wrong?

**Comment by ikbencasdoei** [comment]
Are you using the correct Godot version? For godot-voip 3.0 Godot 3.2.4 is required because it uses a new feature which is only available in that version.

**Comment by drcucaracha** [comment]
If you were using 3.2.3 since 3.2.4 is still unstable and if it works fine thank you and excuse the inconvenience

**Comment by ikbencasdoei** [comment]
If you want to use Godot 3.2.3 you can still use godot-voip version 2.0
