### ISSUE TITLE
Tip for submitting both a demo and an addon from the same repo

### ISSUE THREAD

**Issue by aaronfranke** [c-as/godot-voip#15]
I noticed that you recently submitted [Godot VoIP Demo](https://godotengine.org/asset-library/asset/951) in addition to [Godot VoIP](https://godotengine.org/asset-library/asset/425). Here's a little trick that I use for my assets [GUI in VR Demo](https://godotengine.org/asset-library/asset/604) and [GUI in VR Addon](https://godotengine.org/asset-library/asset/900).

We can use the `.gitattributes` file to tell GitHub to exclude files when generating the ZIP. For GUI in VR Demo, the file looks [like this](https://raw.githubusercontent.com/aaronfranke/godot-GUI-in-VR/master/.gitattributes), with very little excluded. Then, I have a separate "addon" branch for the addon, and all it does is add some more lines to this file to exclude more things, such that it looks [like this](https://raw.githubusercontent.com/aaronfranke/godot-GUI-in-VR/addon/.gitattributes). Any time you update the asset, just rebase this "addon" branch with the added exclusions, force-push, and submit the new commit hashes.

Side note: You should add `eol=lf` to the existing line in your `.gitattributes` so that Git automatically fixes line endings.

**Comment by ikbencasdoei** [comment]
That's a pretty good method. Thanks for the tip!
