### ISSUE TITLE
Not working using Godot 3.3 and Godot 3.4

### ISSUE THREAD

**Issue by AgentSmith0** [c-as/godot-voip#17]
**Godot VoIP version + Godot version:**
I'm using the latest version of Godot VoIP and I tried using Godot 3.3.4 and Godot 3.4.

**OS/device including version:**
Linux 5.14

**Issue description:**
I heard a noise, but the voice wasn't recognizable.

**Steps to reproduce:**
Just try it with Godot 3.3.4 or Godot 3.4.

**Minimal reproduction project:**
N/A

**Comment by rcorre** [comment]
I'm on `Linux 5.15.4-arch1-1`. The plugin works fine for me on 3.3.4, but not at all on 3.4 (`stereo_data` is all `0`).

**Comment by rcorre** [comment]
I can't get `AudioEffectCapture`/`AudioStreamMicrophone` to work in even a simple example in Godot 3.4. I opened https://github.com/godotengine/godot/issues/55315, I think this is an upstream problem.

**Comment by mason-stafford** [comment]
@rcorre 
The following version will settle your problem.
[https://github.com/meisamsafavi/Godot-Enet-VOIP](url)

**Comment by realkotob** [comment]
@meisamsafavi It seems the linked repo does not have code files 🤔

**Comment by mason-stafford** [comment]
@realkotob 
look for the project in my GitHub repository.

**Comment by mason-stafford** [comment]
But I do have a big problem with it.
It's not working on android properly.
Unfortunately.

**Comment by rcorre** [comment]
@meisamsafavi I found https://github.com/meisamsafavi/Godot-Enet-VOIP on your page and its just an empty godot project.
If you want to modify an existing project, you should [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) it instead.

Besides, I was able to reproduce the problem with `AudioEffectCapture` in Godot (https://github.com/godotengine/godot/issues/55315), so I think this can be closed, but I'm not OP.

@AgentSmith0 do you know if your Godot is compiled with `-fPIC`, and if so, have you tried compiling without that flag?

**Comment by mason-stafford** [comment]
@rcorre 
Sorry for the empty project. It's all okay now.
I managed to run the project on Godot 3.4 by changing the WebSocket to Enet.
but the real deal here is it's not compatible with android at all with any version.

**Comment by AgentSmith0** [comment]
> @AgentSmith0 do you know if your Godot is compiled with -fPIC, and if so, have you tried compiling without that flag?

I don't think my Godot was compiled with -fPIC, because I downloaded it from the Godot homepage. And I haven't tried compiling it without that flag.

**Comment by rcorre** [comment]
OK, I suspect I actually encountered a different bug than you, then. By compiling without `-fPIC` I worked around both https://github.com/godotengine/godot/issues/55315 and this issue.

**Comment by AgentSmith0** [comment]
https://github.com/meisamsafavi/Godot-Enet-VOIP works fine for me. Thank you @meisamsafavi, @rcorre and @c-as!

**Comment by mason-stafford** [comment]
@AgentSmith0 Glad to hear it, I hope I can use it on Android successfully soon too. Gonna Let u guys know if it works.

**Comment by ikbencasdoei** [comment]
I'll close this for now. If a similar issue persists please open a new specific issue. I'll probably revert to using Enet in the future, but for now [@meisamsafavi/Godot-Enet-VOIP](https://github.com/meisamsafavi/Godot-Enet-VOIP) seems like a ok alternative.
