### ISSUE TITLE
ENet compatibility

### ISSUE THREAD

**Issue by Calinou** [c-as/godot-voip#18]
As described in [this forum topic](https://godotforums.org/discussion/28333/multiplayer-voice-chat), someone made a fork of this project that adds support for voice chat when using NetworkedMultiplayerENet: https://github.com/meisamsafavi/Godot-Enet-VOIP

Just leaving this here in this case this is of interest.

**Comment by ikbencasdoei** [comment]
Thanks for the notification, I greatly appreciate it.
