### ISSUE TITLE
Not Working on Android Platform

### ISSUE THREAD

**Issue by mason-stafford** [c-as/godot-voip#19]
**Godot VoIP version + Godot version:**
Using recommended 3.3 version

**OS/device including version:**
Android

**Issue description:**
The addone is awesome but unfortunately not working with android at all. I even managed to run it on latest version with Enet.
Running the demo project which is included in project on Windows is perfect and sends the data chunks with 1 or 2 Mega Bytes size. Exporting the exact same demo project for android makes the game lag and sends the data with 6 or 4 Mega Bytes sizes with high latency and the voice is not recognizable at all.
I think it's something related to microphone or data format, mix rate or something like that. I have tested the project with WebSocket and Enet on various version of Godot.

**Steps to reproduce:**
Just Export the apk file of Demo scene of project and run on two android phone and see the result.

**Minimal reproduction project:**

Regards,
Mason

**Comment by tpaulino7** [comment]
Working on Android for me. Don't forget to enable the "Record Audio" and "Capture Audio Output" export permissions.

**Comment by mason-stafford** [comment]
Hi @tpaulino7,
Thanks for responding
All the needed permissions are set.
Would you be kind enough to send me an apk file?
Cause I couldn't make it work with any settings.

Regards
