### ISSUE TITLE
[Feature Request] - encryption

### ISSUE THREAD

**Issue by havi05** [c-as/godot-voip#20]
Add an encryption for the voice chat so that no one can eavesdrop on the voice chat.
This Minecraft plugin uses the AES encryption so maybe it is possible to use it too. 
Minecraft Plugin: https://github.com/henkelmax/simple-voice-chat
Godot Documentation: https://docs.godotengine.org/de/stable/classes/class_aescontext.html

I don't know how performant and how necessary it is, but maybe you could set it up as a separate branch or add a small documentation where it could be added.

**Comment by ikbencasdoei** [comment]
Godot engine networking also has an option for encryption (which will also encrypt this plugins voice data). I suggest try using that.
