### ISSUE TITLE
Buffer consistently growing, making the application lag and unusable

### ISSUE THREAD

**Issue by KatsuroDev** [c-as/godot-voip#21]
**Godot VoIP version + Godot version:**
VoIP: 3.2
Godot: 3.4

**OS/device including version:**
Kubuntu, Manjaro & Windows 10
Kernel: 5.13.0-37-generic & 5.16.2-2-rt19-MANJARO

**Issue description:**
Playback buffer gets bigger over time if consistently sending frames, getting to 100x bigger (Literally).

**Steps to reproduce:**
- Start server
- Put threshold to 0
- Put toggle on
- If alone put Listen on (To send data to the playback buffer)
- Click on speak
- Wait for buffer to grow (less than a minute or two)

**Minimal reproduction project:**
Demo scene

**Potential fix:**
I tried removing these [lines](https://github.com/c-as/godot-voip/blob/4efda2b88927d5143d57973b6345d6de5da73c32/addons/godot-voip/scripts/voice_instance.gd#L68-L71), and it seemed to work well, no audio anomalies, which I got before removing these lines.
It seems you are pushing as much frames as there is in the playback buffer if there is, with no data. Which if it is the cases, would only make the buffer grow exponentially.

https://github.com/c-as/godot-voip/blob/4efda2b88927d5143d57973b6345d6de5da73c32/addons/godot-voip/scripts/voice_instance.gd#L68-L71

**Comment by mason-stafford** [comment]
Huge thanks.
but it's on the receiving side, buffer grows on sender side.
It's not gonna fix it.
@KatsuroDev @c-as 
I'm working on a solution and I will be grateful for any.
