### ISSUE TITLE
Compatibility with Godot 3.5

### ISSUE THREAD

**Issue by AgentSmith0** [c-as/godot-voip#25]
Is this plugin compatible with Godot 3.5?
Thank you!

**Comment by ikbencasdoei** [comment]
Woops, I'm so sorry for not responding, but I'm sure you've seen the plugin works great on 3.5!

**Comment by AgentSmith0** [comment]
Unfortunately It doesn't seem to work in Godot 3.5, I can only hear some kind of beep tone. It worked well in Godot 3.4.5, could you have a look at this problem?

**Comment by ikbencasdoei** [comment]
Have you tried using the master branch?

**Comment by AgentSmith0** [comment]
I've updated the addon in my project with the files from this branch: https://github.com/c-as/godot-voip/tree/3.0. It works fine now. Thank you!

**Comment by c-as** [comment]
Great!
