### ISSUE TITLE
Crashes Godot on my Windows 10 Machine

### ISSUE THREAD

**Issue by bestdani** [c-as/godot-voip#4]
This approach looked very promising unfortunately I noticed cracks and pops in the sound probably from the microphone de / activation process involved in this.

(and when I use the microphone effect like that on my (and others) machines running Windows 10 in some more sophisticated application, we suffered from Godot Engine crashes which seemed to be caused by the microphone effect but for now it was not really possible to tackle these crashes down to the exact point of failure)

**Comment by ikbencasdoei** [comment]
Have not been able to reproduce this problem. Likely a internal Godot issue if it still exists.
