### ISSUE TITLE
Update 3.2.4 / 4.0  -> real time VoIP

### ISSUE THREAD

**Issue by havi05** [c-as/godot-voip#6]
Can you update this cool project to the newest Godot version (Realese Candidate) which supports realtime VoIP data?
(see: https://github.com/godotengine/godot/pull/45593)

Gamemap

**Comment by ikbencasdoei** [comment]
Thanks! This looks very promising.

**Comment by havi05** [comment]
Please write when you are done.

**Comment by ikbencasdoei** [comment]
I'm working on the 3.0 branch

**Comment by ikbencasdoei** [comment]
I opened a pull request on the new version #7
